### ISSUE TITLE
Changing the palette should bring back the process button

### ISSUE THREAD

**Issue by BrewingWeasel** [ziap/repalette#1]
I saw that you recently made the process button turn into a download button once the image had been processed in order to make it more friendly on mobile. But right now when you change the palette or the dither strategy, the download button remains and you can no longer process the image. This makes it really annoying to try out different palettes or dither strategies with the same image, because you have to reload the site and reupload the image. Because of this, I think changing the palette or dither strategy should revert the download button back into the process button. (Or potentially there could just be two buttons)

Anyways, great project, I'll definitely be using it to match my wallpapers more closely to my color palette!

**Comment by ziap** [comment]
Thank you for trying out my project. I prefer having two buttons because it's a more straightforward solution. I am going to change it as soon as possible.

**Comment by ziap** [comment]
Fixed with 2cc6a4d725ff6458e4fd1d4f8be732095ad5c1a4
